services:
  - type: web
    name: quarry-management
    env: python
    buildCommand: pip install -r requirements.txt && alembic upgrade head
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: quarry-db
          property: connectionString
    plan: free
databases:
  - name: quarry-db
    databaseName: quarry
    user: quarry_user
    plan: free